# Generated by Django 5.0.6 on 2025-01-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_sixdigitcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sixdigitcode',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
