# Generated by Django 5.0.6 on 2024-12-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
