# Generated by Django 5.0.6 on 2024-12-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='issued_at',
            field=models.DateTimeField(),
        ),
    ]
