# Generated by Django 5.0.6 on 2024-12-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_purchase_issued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
