# Generated by Django 5.0.6 on 2024-12-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_purchase_issued_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table='edtech_payment_purchase_v2',
        ),
    ]
