# Generated by Django 5.0.6 on 2024-12-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_purchase_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
