# Generated by Django 5.0.6 on 2024-12-08 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment'),
        ('productmanagement', '0001_initial'),
        ('sales', '0005_rename_link_channel_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasev3',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.channel'),
        ),
        migrations.AlterField(
            model_name='purchasev3',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productmanagement.product'),
        ),
        migrations.AlterField(
            model_name='purchasev3',
            name='tracker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymenttracker'),
        ),
        migrations.AlterField(
            model_name='purchasev3',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
