# Generated by Django 5.0.6 on 2024-12-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0007_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='pos',
            field=models.CharField(choices=[('adjectives', 'adjectives'), ('nouns', 'nouns')], max_length=10),
        ),
    ]
