# Generated by Django 5.0.6 on 2024-12-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesPartner',
        ),
    ]
