# Generated by Django 5.0.6 on 2024-12-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
