# Generated by Django 5.0.6 on 2024-12-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_channel_coupon_code_alter_channel_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='link',
            new_name='key',
        ),
    ]
